server:
  port: 8086
spring:
  application:
    name: bank-earnings-service
  datasource:
    url: jdbc:postgresql://localhost:5432/earnings_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
application:
  secret-key: agsnrigabeorignaiogrngisrbnjvkdxfbnjksznfoseringsioerngioserngklzfndbsblzhnfkvanfglkaern
  internal-token: oyuwitystyvstdvsdytvdsyvv7621vgfztrxcnvjzgxvdz
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
