spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://10.10.50.91:8761/eureka
