spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallets_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: wallet-service
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
application:
  secret-key: agsnrigabeorignaiogrngisrbnjvkdxfbnjksznfoseringsioerngioserngklzfndbsblzhnfkvanfglkaern
  internal-token: oyuwitystyvstdvsdytvdsyvv7621vgfztrxcnvjzgxvdz
rabbitmq:
  exchange: exchange
  queue:
    commission-queue: commission-queue
  routing-key:
    commission-key: commission-key
axon:
  serializer:
    general: jackson
  eventhandling:
    processors:
      my-processor:
        mode: tracking
