server:
  port: 8888
spring:
  application:
    name: audit-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/audit_db
eureka:
  client:
    service-url.defaultZone:
      http://localhost:8761/eureka
