version: '3.9'
name: wallet
services:
  db:
    image: postgres:16.3-alpine3.20
    container_name: db
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallets_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    name: wallets-db-data
