server:
  port: 8085
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/products_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: yaroslav.radevych.vynnytskyi@nerdysoft.com
    password: wsvp xuwv dlpe qrrj
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
application:
  secret-key: agsnrigabeorignaiogrngisrbnjvkdxfbnjksznfoseringsioerngioserngklzfndbsblzhnfkvanfglkaern
  internal-token: oyuwitystyvstdvsdytvdsyvv7621vgfztrxcnvjzgxvdz
mail:
  subject:
    loan-limit: "[Action Required] Overdue Payment Notice for Your Loan Limit"
    deposit: "Your Deposit is Now Available for Withdrawal!"
  body:
    loan-limit: "This is a friendly reminder that your loan limit repayment was not done. Our records 
          indicate that the payment has not yet been received. If we do not receive the payment within
          the next few days, you may continue receiving daily reminders, and further actions may be taken."
    deposit: "We are pleased to inform you that your deposit has matured, and you can now withdraw your funds, 
    including any earned interest. Please note that you have 10 days from the receipt of this email to complete
     the withdrawal. If no action is taken within this period, your funds will be frozen again for 4 months."
axon:
  serializer:
    general: jackson
