server:
  port: 8080
spring:
  application:
    name: account-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/accounts_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url.defaultZone:
      http://localhost:8761/eureka
rabbitmq:
  transaction:
    exchange:
      transaction-exchange
    queue:
      transaction-queue
    routing_key:
      transaction-key
