server:
  port: 8080
spring:
  application:
    name: account-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/accounts_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
wallet:
  service:
    url: http://10.10.50.166:8080
