server:
  port: 8082
spring:
  application:
    name: currency-exchange-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/exchange_db
external:
  api:
    exchange:
      url: https://v6.exchangerate-api.com/v6/f587d1b33cdefe0a90641bae/latest/
eureka:
  client:
    service-url.defaultZone:
      http://localhost:8761/eureka
application:
  secret-key: agsnrigabeorignaiogrngisrbnjvkdxfbnjksznfoseringsioerngioserngklzfndbsblzhnfkvanfglkaern
  internal-token: oyuwitystyvstdvsdytvdsyvv7621vgfztrxcnvjzgxvdz
axon:
  serializer:
    general: jackson
