spring:
  application:
    name: currency-exchange-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/exchange_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

external:
  api:
    exchange:
      url: https://v6.exchangerate-api.com/v6/25c384179a8f196917319899/latest/
