spring:
  application:
    name: currency-exchange-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/exchange_db
external:
  api:
    exchange:
      url: https://v6.exchangerate-api.com/v6/25c384179a8f196917319899/latest/
